#ifndef DEFINE_SWITCHES_HPP
#define DEFINE_SWITCHES_HPP

#define TEST_ONLY
#define DEBUG
//#define DEBUG_READ_TEXT
//#define DEBUG_ENTRY_SPLIT
//#define DEBUG_TEXT_SPLIT

#endif // DEFINE_SWITCHES_HPP
